### ISSUE TITLE
Add a small hole to poke the ball bearing out

### ISSUE THREAD

**Issue by igiannakas** [IRTrail/G2E-Filametrix#10]
Unfortunately my Amazon sourced ball bearings were ever so slightly larger than 5.5 mm causing them to nearly fit in the holes. However I now cannot get them out in order to ream the hole a little bit for the ball bearings to fit comfortably.

May I add a suggestion to add a 2mm hole opposite from the ball bearings as an aid to remove them? Pushing them out using some spare filament or a small tool bit.

**Comment by IRTrail** [comment]
Ever so slightly as in 5.505mm or 6.005mm? The bore is 6mm and the balls should be a literal drop in fit. They should sound like a baby rattle after the switch is installed and you shake the part.
