### ISSUE TITLE
Parts list?

### ISSUE THREAD

**Issue by arnoldstrife** [IRTrail/G2E-Filametrix#4]
Hi, is there a parts list? It seems the filament detection is Ball and Microswitch, but I'm not sure of what size ball bearing or Microswitch should be used. Or if there are any other parts needed? The original Filametrix didn't have a sensor, and I'm assuming most of the screws remain the same in G2E but with the additional lever screws in Filametrix, but additional documentation for that would be great.

**Comment by IRTrail** [comment]
Updated readme to include switch types and ball bearing diameters. Hope it helps you out.
