### ISSUE TITLE
Revo Voron Hotend request

### ISSUE THREAD

**Issue by discreteaudio** [IRTrail/G2E-Filametrix#5]
Would love to build your design to go with my ERCF v2.  Unfortunately, I don't see the Revo Voron as an option.  Any chance to add it to the mix?  I don't see the "Other Printhead" folder you mention either.

**Comment by IRTrail** [comment]
Check it ooooouuuuut!

https://github.com/IRTrail/G2E-Filametrix/tree/main/Printheads/Revo

Let me know if there are any issues with it. I just revised the CAD and haven't printed one myself.

**Comment by discreteaudio** [comment]
I'll give it a go as soon as my current print finishes up!  Looking forward to the build for sure!  Thanks for the rapid response!

**Comment by discreteaudio** [comment]
Got it printed last night.  Hoping to put it together this weekend after a trip to the hardware store for misc hardware.  I will keep you posted on progress.  So far everything looks fantastic.

**Comment by discreteaudio** [comment]
![PXL_20240224_081552421](https://github.com/IRTrail/G2E-Filametrix/assets/55968686/d5a256b5-31f0-4e7a-a335-aa1d7cb6295d)
![PXL_20240224_081556167](https://github.com/IRTrail/G2E-Filametrix/assets/55968686/fcc08c40-2a2a-4c70-a911-f699616f2aaa)
![PXL_20240224_081606786](https://github.com/IRTrail/G2E-Filametrix/assets/55968686/0b4d159b-2907-4994-868e-c626ddc51d10)

I had to file out material to allow the arm to have enough travel to cut filament and retract easily.  If you edit the design, take out the black bit.

**Comment by IRTrail** [comment]
Thanks for the pictures. I added a recess to help with that. I just pushed it, so give that a try to see what you think.

**Comment by discreteaudio** [comment]
That did the trick!  Now to finish building everything.  LoL
Thanks again!
